### PR TITLE
Implement tableabsolute message format

### PR DESCRIPTION
**Pull request by therealprof**
For comparison (read: diff) purposes it's much better to not have the
percentages in the output.

Signed-off-by: Daniel Egger <daniel@eggers-club.de>

### CODE REVIEW

**Comment by RazrFalcon** [comment]
Hi. What exactly does it change? Can you provide an output example and explain why this output format needed?

**Comment by therealprof** [comment]
Sure. With the regular table output format you would get something like this:
```
Compiling ...
Analyzing target/debug/cargo-bloat
 File  .text     Size        Crate Name
 1.2%   2.9%  32.8KiB         json json::parser::Parser::parse
 0.5%   1.2%  13.8KiB  cargo_bloat cargo_bloat::parse_args
 0.5%   1.1%  12.7KiB         json json::codegen::Generator::write_json
 0.5%   1.1%  12.6KiB  cargo_bloat cargo_bloat::process_crate
 0.4%   1.0%  11.3KiB         json json::util::print_dec::write
 0.4%   0.9%  10.5KiB    [Unknown] _read_line_info
 0.3%   0.7%   8.3KiB          std std::sys::unix::process::process_common::Command::capture_env
 0.3%   0.7%   7.4KiB          std ___rdos_backtrace_dwarf_add
 0.2%   0.5%   5.4KiB    [Unknown] __mh_execute_header
 0.2%   0.5%   5.2KiB          std <rustc_demangle::legacy::Demangle as core::fmt::Display>::fmt
 0.2%   0.4%   5.0KiB          std rustc_demangle::demangle
 0.2%   0.4%   4.8KiB  cargo_bloat cargo_bloat::main
 0.2%   0.4%   4.8KiB  cargo_bloat cargo_bloat::demangle::v0::Printer::print_path
 0.2%   0.4%   4.8KiB    [Unknown] _read_attribute
 0.2%   0.4%   4.5KiB          std core::num::flt2dec::strategy::dragon::format_shortest
 0.2%   0.4%   4.4KiB          std alloc::collections::btree::map::BTreeMap<K,V>::insert
 0.2%   0.4%   4.4KiB         json json::object::Object::insert_index
 0.2%   0.4%   4.1KiB  cargo_bloat cargo_bloat::wrapper_mode
 0.2%   0.4%   4.1KiB cargo_bloat? <cargo_bloat::demangle::legacy::Demangle as core::fmt::Display>::fmt
 0.2%   0.4%   4.1KiB  cargo_bloat cargo_bloat::print_methods_table
35.6%  85.2% 952.7KiB              And 5431 smaller methods. Use -n N to show more.
41.8% 100.0%   1.1MiB              .text section size, the file size is 2.6MiB
```

If you choose absolute table you would get this:
```
Compiling ...
Analyzing target/debug/cargo-bloat
    Size        Crate Name
 32.8KiB         json json::parser::Parser::parse
 13.8KiB  cargo_bloat cargo_bloat::parse_args
 12.7KiB         json json::codegen::Generator::write_json
 12.6KiB  cargo_bloat cargo_bloat::process_crate
 11.3KiB         json json::util::print_dec::write
 10.5KiB    [Unknown] _read_line_info
  8.3KiB          std std::sys::unix::process::process_common::Command::capture_env
  7.4KiB          std ___rdos_backtrace_dwarf_add
  5.4KiB    [Unknown] __mh_execute_header
  5.2KiB          std <rustc_demangle::legacy::Demangle as core::fmt::Display>::fmt
  5.0KiB          std rustc_demangle::demangle
  4.8KiB  cargo_bloat cargo_bloat::main
  4.8KiB  cargo_bloat cargo_bloat::demangle::v0::Printer::print_path
  4.8KiB    [Unknown] _read_attribute
  4.5KiB          std core::num::flt2dec::strategy::dragon::format_shortest
  4.4KiB          std alloc::collections::btree::map::BTreeMap<K,V>::insert
  4.4KiB         json json::object::Object::insert_index
  4.1KiB  cargo_bloat cargo_bloat::wrapper_mode
  4.1KiB cargo_bloat? <cargo_bloat::demangle::legacy::Demangle as core::fmt::Display>::fmt
  4.1KiB  cargo_bloat cargo_bloat::print_methods_table
952.7KiB              And 5431 smaller methods. Use -n N to show more.
  1.1MiB              .text section size, the file size is 2.6MiB
```

Now if you're interested in analysing the impact a change has on generated code you might do something like me and record the output into a file and then run `diff` over it. With the regular table output this has the problem that the the percentages might change which means that diff will consider ever line of the output changed which makes it hard to do a quick analysis, especially when absolute numbers change at the same time.

**Comment by RazrFalcon** [comment]
If the sole purpose of this change is to simplify the diff, than the diff should be implemented in the app itself. The regular diff will not handle cases when method moved up or down.

I guess you want something like [this](https://github.com/google/bloaty#size-diffs)? I wanted to implement this for a long time, but was not sure if someone really need this. And it's not an easy task.

**Comment by therealprof** [comment]
> The regular diff will not handle cases when method moved up or down.

Lines moving up and down is totally fine. That's exactly what I would expect to see.

> I guess you want something like this? I wanted to implement this for a long time, but was not sure if someone really need this. And it's not an easy task.

Yeah, the problem is I don't really want to copy/keep old binaries around and figuring out the right binary after the fact is non trivial even if they still exist in the target dir...

I really would like to keep things simple and this new format is simple. The alternative for me would be to use JSON and implement a custom diff command based on that.

**Comment by RazrFalcon** [comment]
I see. Than instead of making a custom message format we should add a flag like `--no-relative-size`. That will simply remove *File* and *.text* columns. If this is fine by you I will make this change right now.

**Comment by therealprof** [comment]
>  If this is fine by you I will make this change right now.

Sounds great. I was actually doing that myself before I noticed that you added the `message-format` feature for JSON which seemed like a much simpler way to achieve the same.

**Comment by RazrFalcon** [comment]
Ok.

I think that `--message-format` isn't the right place since `--no-relative-size` will not affect the `--time` output.

**Comment by therealprof** [comment]
> I think that --message-format isn't the right place since --no-relative-size will not affect the --time output.

I don't follow, if there's no relative size to start with it's totally sane to still say "only give me absolute values". But either way is fine, I was under the impression that this was the way to add new output formats but if you say you want to make similar ones configurable instead that'll make it a more useful tool, too.

Thanks for all the hard work on that tool; it's insanely useful to me.

**Comment by RazrFalcon** [comment]
Done.

For me, `--message-format` is just for table/json. The actual table tweaking should be done via different flags.

**Comment by therealprof** [comment]
Excellent, thanks!

However I'd like to add that I find the command line option explanation
```
        --no-relative-size          Hide 'File' and '.text' columns
```
less ideal because it obviously only applies to message-format tables.

**Comment by RazrFalcon** [comment]
`--message-format=json` doesn't support relative sizes from the start, so...

**Comment by therealprof** [comment]
> --message-format=json doesn't support relative sizes from the start, so...

That's exactly my point: Having an general option which only applies to tables is potentially confusing.

**Comment by RazrFalcon** [comment]
The table output is the primary one, so it's fine for now.

**Pull request closed without merging**
